Pipeline ภาพรวม

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [54]:
from google.colab import userdata
userdata.get('GOOGLE_API_KEY')

'AIzaSyBN-JCrfWfzvaNbzj7pWqbF8Ozg3yAi8BI'

In [56]:
import glob
import os

red = glob.glob(os.path.join("/content/drive/MyDrive/H3_datanaja/data"))
red

['/content/drive/MyDrive/H3_datanaja/data']

In [88]:
# Gemini setup removed by user request. Using Typhoon only.

#📁 Section 0: Setup & LLM Test

In [57]:
!pip install -q sentence-transformers pythainlp rank-bm25 requests python-dotenv

In [58]:
import os, csv, re, time, requests
import numpy as np
from pathlib import Path
from google.colab import userdata

THAILLM_API_KEY = userdata.get('ThaiLLM')

In [59]:
!curl http://thaillm.or.th/api/typhoon/v1/chat/completions -H "Content-Type: application/json" -H "apikey: jsakIuGWRcGOwWWXIazfofGUG1hidgof" -d '{"model": "/model", "messages": [{"role": "user", "content": "สวัสดี"}], "max_tokens": 2048, "temperature": 0.3}'

{"id":"chatcmpl-7bfb58aba48ee76336d9454c69ab1727","object":"chat.completion","created":1774697279,"model":"/model","choices":[{"index":0,"message":{"role":"assistant","content":"สวัสดีครับ! 😊 ยินดีที่ได้พบคุณ วันนี้มีอะไรให้ช่วยไหมครับ?","refusal":null,"annotations":null,"audio":null,"function_call":null,"tool_calls":[],"reasoning":null,"reasoning_content":null},"logprobs":null,"finish_reason":"stop","stop_reason":null,"token_ids":null}],"service_tier":null,"system_fingerprint":null,"usage":{"prompt_tokens":12,"total_tokens":51,"completion_tokens":39,"prompt_tokens_details":null},"prompt_logprobs":null,"prompt_token_ids":null,"kv_transfer_params":null}

In [8]:
!curl http://thaillm.or.th/api/typhoon/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "apikey: jsakIuGWRcGOwWWXIazfofGUG1hidgof" \
  -d '{"model": "/model", "messages": [{"role": "user", "content": "สวัสดี"}], "max_tokens": 2048, "temperature": 0.3}'

{"id":"chatcmpl-2a6bbe347b0ced468df2c21ba135a7b8","object":"chat.completion","created":1774677006,"model":"/model","choices":[{"index":0,"message":{"role":"assistant","content":"สวัสดีครับ! 😊 ยินดีที่ได้พบกันครับ คุณมีคำถามหรือต้องการความช่วยเหลืออะไรไหมครับ?","refusal":null,"annotations":null,"audio":null,"function_call":null,"tool_calls":[],"reasoning":null,"reasoning_content":null},"logprobs":null,"finish_reason":"stop","stop_reason":null,"token_ids":null}],"service_tier":null,"system_fingerprint":null,"usage":{"prompt_tokens":12,"total_tokens":58,"completion_tokens":46,"prompt_tokens_details":null},"prompt_logprobs":null,"prompt_token_ids":null,"kv_transfer_params":null}

In [73]:
import requests
from google.colab import userdata

# ใช้ API Key ที่คุณตั้งไว้ใน Userdata หรือใช้ค่าตรง
API_KEY = userdata.get('ThaiLLM') if userdata.get('ThaiLLM') else "jsakIuGWRcGOwWWXIazfofGUG1hidgof"
URL = "http://thaillm.or.th/api/typhoon/v1/chat/completions"

def get_typhoon_response(prompt):
    headers = {
        "Content-Type": "application/json",
        "apikey": API_KEY
    }
    data = {
        "model": "/model",
        "messages": [
            {"role": "system", "content": "You are a male AI assistant named Typhoon created by SCB 10X to be helpful, harmless, and honest."},
            {"role": "user", "content": prompt}
        ],
        "max_tokens": 512,
        "temperature": 0.3
    }

    response = requests.post(URL, headers=headers, json=data)
    if response.status_code == 200:
        return response.json()['choices'][0]['message']['content']
    else:
        return f"Error: {response.status_code} - {response.text}"

# ทดสอบขอสูตรไก่ย่าง
prompt = "ขอสูตรไก่ย่าง"
print(get_typhoon_response(prompt))

Error: 504 - <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>

<title>thaillm.or.th | 504: Gateway time-out</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" />
</head>
<body>
<div id="cf-wrapper">
    <div id="cf-error-details" class="p-0">
        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
                <span class="inline-block">Gateway time-out</span>
                <span class="code-label">Error code 504</span>
            </h1>
            <div>
                Visit <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_504&utm_campaign=thaillm.or.th" target="_blank" rel="noopener noreferrer">cloudflare.com</a> for more information.
            </div>
            <div class="mt-3">2026-03-28 12:20:51 UTC</div>
        </header>
        <div class="my-8 bg-gradient-gray">
            <div class="w-240 lg:w-full mx-auto">
                <div class="clearfix md:px-8">
                    <div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">

    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>

  </div>
  <span class="md:block w-full truncate">You</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">

    Browser

  </h3>

  <span class="leading-1.3 text-2xl text-green-success">Working</span>

</div>
                    <div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_504&#38;utm_campaign=thaillm.or.th" target="_blank" rel="noopener noreferrer">
    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    </a>
  </div>
  <span class="md:block w-full truncate">Seattle</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
  <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_504&utm_campaign=thaillm.or.th" target="_blank" rel="noopener noreferrer">
    Cloudflare
  </a>
  </h3>

  <span class="leading-1.3 text-2xl text-green-success">Working</span>

</div>
                    <div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">

    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>

  </div>
  <span class="md:block w-full truncate">thaillm.or.th</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">

    Host

  </h3>

  <span class="leading-1.3 text-2xl text-red-error">Error</span>

</div>
                </div>
            </div>
        </div>

        <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
            <div class="clearfix">
                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                    <p>The web server reported a gateway time-out error.</p>
                </div>
                <div class="w-1/2 md:w-full float-left leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                    <p class="mb-6">Please try again in a few minutes.</p>
                </div>
            </div>
        </div>

        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
    <p class="text-13">
      <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">9e3695e73d49fc2f</strong></span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
      <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
        Your IP:
        <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
        <span class="hidden" id="cf-footer-ip">136.118.53.213</span>
        <span class="cf-footer-separator sm:hidden">&bull;</span>
      </span>
      <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_504&#38;utm_campaign=thaillm.or.th" id="brand_link" target="_blank">Cloudflare</a></span>

    </p>
    <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
  </div><!-- /.error-footer -->

    </div>
</div>
</body>
</html>

In [63]:
import requests
import json
import time
import re

def ask_llm(messages, model="pathumma", max_retries=5):
    """Call ThaiLLM API with retry and rate-limit handling.

    Available models: typhoon, openthaigpt, pathumma, kbtg
    """
    url = f"http://thaillm.or.th/api/{model}/v1/chat/completions"
    headers = {"Content-Type": "application/json", "apikey": THAILLM_API_KEY}
    payload = {
        "model": "/model",
        "messages": messages,
        "max_tokens": 2048,
        "temperature": 0,
    }

    for attempt in range(max_retries):
        try:
            resp = requests.post(url, headers=headers, json=payload, timeout=120)

            # Rate limit — wait and retry
            if resp.status_code == 429:
                wait = min(2 ** attempt, 30)
                print(f"  Rate limited, waiting {wait}s...")
                time.sleep(wait)
                continue

            resp.raise_for_status()
            return resp.json()["choices"][0]["message"]["content"].strip()

        except requests.exceptions.RequestException as e:
            wait = 2 ** attempt
            print(f"  Error: {e}, retrying in {wait}s...")
            time.sleep(wait)

    return None


def parse_answer(text):
    """Extract answer number (1-10) from LLM response."""
    if text is None:
        return None

    # ลบส่วน <think>...</think> ออกถ้ามี
    clean = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()

    # ค้นหาแพทเทิร์น ANSWER: X
    m = re.search(r"ANSWER:\s*(\d+)", clean, re.IGNORECASE)
    if m:
        val = int(m.group(1))
        if 1 <= val <= 10: return val

    # ถ้าไม่เจอ ให้ค้นหาตัวเลขโดดๆ ตัวแรกที่อยู่ในช่วง 1-10
    nums = re.findall(r"\b(\d{1,2})\b", clean)
    for n in nums:
        val = int(n)
        if 1 <= val <= 10: return val

    return None

## Setting up RAG for 'Thailand's Electronics Store'

To allow the LLM to answer questions about 'Thailand's electronics store', we need to provide it with a knowledge base using RAG. This involves defining the store's information, chunking it, embedding it, and retrieving relevant parts based on a query.

In [14]:
store_knowledge = [
    {"type": "store_name", "content": "Thailand's electronics store"},
    {"type": "house_brand", "name": "SaiFah", "description": "High-performance and innovative electronic gadgets."},
    {"type": "house_brand", "name": "DaoNuea", "description": "Reliable and affordable electronics for everyday use."},
    {"type": "house_brand", "name": "KluenSiang", "description": "Premium audio equipment for an immersive sound experience."},
    {"type": "house_brand", "name": "WongKhoJon", "description": "Durable and rugged devices for outdoor enthusiasts."},
    {"type": "house_brand", "name": "JudChuem", "description": "Smart home devices and connectivity solutions."},
    {"type": "product_category", "name": "Phones", "description": "Smartphones from various brands, including SaiFah and DaoNuea."},
    {"type": "product_category", "name": "Laptops", "description": "Laptops for work, gaming, and everyday use, featuring SaiFah models."},
    {"type": "product_category", "name": "Audio", "description": "Headphones, speakers, and soundbars from KluenSiang and other brands."},
    {"type": "product_category", "name": "Wearables", "description": "Smartwatches and fitness trackers from SaiFah and WongKhoJon."},
    {"type": "product_category", "name": "Accessories", "description": "Chargers, cases, cables, and other electronics accessories."},
    {"type": "branch", "name": "Siam", "location": "Bangkok", "details": "Our flagship store in the heart of Bangkok."},
    {"type": "branch", "name": "Lad Phrao", "location": "Bangkok", "details": "Conveniently located for northern Bangkok residents."},
    {"type": "branch", "name": "Rama 9", "location": "Bangkok", "details": "A modern branch catering to the vibrant Rama 9 area."},
    {"type": "branch", "name": "Chiang Mai", "location": "Chiang Mai", "details": "Serving our customers in the northern region."},
    {"type": "branch", "name": "Phuket", "location": "Phuket", "details": "Our southern branch, perfect for locals and tourists."}
]

# Combine information into a list of strings for easier chunking
knowledge_chunks_raw = []
for item in store_knowledge:
    if item["type"] == "store_name":
        knowledge_chunks_raw.append(f"The store is called {item['content']}.")
    elif item["type"] == "house_brand":
        knowledge_chunks_raw.append(f"Our house brand {item['name']} offers {item['description']}")
    elif item["type"] == "product_category":
        knowledge_chunks_raw.append(f"In the {item['name']} category, we have {item['description']}")
    elif item["type"] == "branch":
        knowledge_chunks_raw.append(f"Our {item['name']} branch is located in {item['location']}. {item['details']}")

print("Initial knowledge chunks prepared:")
for i, chunk in enumerate(knowledge_chunks_raw[:5]):
    print(f"- {chunk}")
print(f"... and {len(knowledge_chunks_raw) - 5} more chunks.")

Initial knowledge chunks prepared:
- The store is called Thailand's electronics store.
- Our house brand SaiFah offers High-performance and innovative electronic gadgets.
- Our house brand DaoNuea offers Reliable and affordable electronics for everyday use.
- Our house brand KluenSiang offers Premium audio equipment for an immersive sound experience.
- Our house brand WongKhoJon offers Durable and rugged devices for outdoor enthusiasts.
... and 11 more chunks.

### ✅Test the LLM without RAG

Let's ask a FahMai-specific question *without* any context. The LLM shouldn't know the answer.

In [13]:
# Ask without context — LLM has no idea about FahMai's products
response = ask_llm([
    {"role": "user", "content": "Watch S3 Ultra กันน้ำได้กี่ ATM ครับ?"}
])
print("LLM response (no context):", response)
print("\n→ The LLM doesn't know FahMai-specific facts. We need RAG!")

LLM response (no context): <think>
Okay, the user is asking about the water resistance rating of the Samsung Galaxy S3 Ultra. Let me start by recalling what I know about the S3 Ultra. Wait, actually, the Galaxy S3 Ultra is a variant of the Galaxy S3, but I need to confirm if it's a real model or a different name. Maybe it's a local version or a different carrier's model. The original Galaxy S3 was released in 2012, and its water resistance was IP67, which means it can be submerged in up to 1 meter of water for up to 30 minutes. But the S3 Ultra might have a different rating.

I should check if the S3 Ultra has a different IP rating. Sometimes manufacturers add "Ultra" to indicate a more rugged or water-resistant version. For example, the Galaxy S7 and S8 have IP68 ratings. However, the S3 Ultra might not be as advanced. Let me think. The original S3 was IP67, but maybe the Ultra version has a higher rating. Alternatively, it could be that the S3 Ultra is a different model altogether, perhaps with a higher IP rating.

Wait, I should verify this. If I'm not sure, I should state that the S3 Ultra's water resistance might vary by region or carrier. But generally, the original S3 was IP67. However, some sources mention that the S3 Ultra has an IP67 rating as well. Alternatively, maybe it's IP68. I need to be careful here. Let me recall: the Galaxy S3 Ultra was released in 2013, and some reports say it has an IP67 rating. But I should check if there's any official information.

Alternatively, maybe the user is referring to a different model. If the S3 Ultra isn't a real model, perhaps they meant the Galaxy S3, and the answer would be IP67. But if it's a real model, maybe it's IP68. However, I need to be accurate. Let me think again. The Galaxy S3 Ultra was indeed a model, but I'm not entirely sure about its exact IP rating. Some sources indicate that it's IP67, while others might say IP68. To avoid giving incorrect information, I should mention that the S3 Ultra's water resistance can vary and suggest checking the official specifications or contacting Samsung support for the most accurate details.

Alternatively, if I'm certain that the S3 Ultra has an IP67 rating, I can state that. But I need to be cautious. Let me cross-verify. A quick search in my memory: the Galaxy S3 Ultra was released in 2013, and some reviews mention it has an IP67 rating, which allows submersion up to 1 meter for 30 minutes. However, other sources might say it's IP68. Since I can't access external data, I have to rely on existing knowledge.

In conclusion, the safest answer is to state that the Galaxy S3 Ultra has an IP67 rating, which means it can withstand water immersion up to 1 meter for 30 minutes. However, it's important to note that this is not a guarantee, and using the device in water can still cause damage. Also, the rating might vary depending on the region or carrier. Advise the user to check the official documentation or contact Samsung support for the most accurate information.
</think>
Samsung Galaxy S3 Ultra มีค่ากันน้ำ IP67 ซึ่งหมายความว่าสามารถทนต่อการแช่ในน้ำลึก 1 เมตรได้นานถึง 30 นาที อย่างไรก็ตาม นี่ไม่ใช่การรับประกันว่าอุปกรณ์จะไม่เสียหายเมื่อสัมผัสน้ำ และควรหลีกเลี่ยงการใช้งานในสภาพแวดล้อมที่มีน้ำอย่างต่อเนื่อง ค่า IP67 ยังหมายถึงการป้องกันฝุ่นระดับสูงอีกด้วย หากต้องการข้อมูลที่แน่นอน แนะนำให้ตรวจสอบเอกสารทางการของ Samsung หรือติดต่อฝ่ายสนับสนุนลูกค้าเพื่อยืนยันคุณสมบัติเฉพาะของรุ่นที่คุณมี

→ The LLM doesn't know FahMai-specific facts. We need RAG!

### 📌Load Questions

In [33]:
questions = []
with open(f"{DATA_DIR}/questions.csv", encoding="utf-8") as f:
    for row in csv.DictReader(f):
        choices = {str(i): row[f"choice_{i}"] for i in range(1, 11)}
        questions.append({"id": int(row["id"]), "question": row["question"], "choices": choices})

print(f"Loaded {len(questions)} questions")
print(f"\nExample — Q1: {questions[0]['question']}")
for k, v in questions[0]["choices"].items():
    print(f"  {k}. {v}")

Loaded 100 questions

Example — Q1: Watch S3 Ultra กันน้ำได้กี่ ATM ครับ
  1. 3 ATM
  2. IP68
  3. 5 ATM
  4. IP67
  5. 10 ATM
  6. 20 ATM
  7. IPX8
  8. 1 ATM
  9. ไม่มีข้อมูลนี้ในฐานข้อมูล
  10. คำถามนี้ไม่เกี่ยวข้องกับฐานข้อมูลสินค้า

### 😎1.1 Load Knowledge Base

In [29]:
from pathlib import Path

KB_DIR = Path("/content/drive/MyDrive/H3_datanaja/data/knowledge_base") # Define KB_DIR here

documents = []
for fp in sorted(KB_DIR.rglob("*.md")):
    text = fp.read_text(encoding="utf-8")
    documents.append({"path": str(fp.relative_to(KB_DIR)), "text": text})

print(f"Loaded {len(documents)} documents")
print(f"  products/: {sum(1 for d in documents if 'products/' in d['path'])}")
print(f"  policies/: {sum(1 for d in documents if 'policies/' in d['path'])}")
print(f"  store_info/: {sum(1 for d in documents if 'store_info/' in d['path'])}")

# Preview one document only if documents exist
if documents:
    print(f"\n--- Sample: {documents[0]['path']} ---")
    print(documents[0]["text"][:500])
else:
    print("\nNo documents loaded to preview.")

Loaded 118 documents
  products/: 110
  policies/: 5
  store_info/: 3

--- Sample: policies/cancellation_policy.md ---
# นโยบายการยกเลิกคำสั่งซื้อ — ร้านฟ้าใหม่

**วันที่อัปเดต:** 1 มีนาคม 2569

---

## 1. ภาพรวมนโยบาย

ฟ้าใหม่เข้าใจว่าบางครั้งลูกค้าอาจต้องการยกเลิกคำสั่งซื้อด้วยเหตุผลต่างๆ นโยบายนี้อธิบายสิทธิ์และขั้นตอนการยกเลิกคำสั่งซื้อตามสถานะของคำสั่งซื้อในขณะนั้น ความสามารถในการยกเลิกขึ้นอยู่กับสถานะคำสั่งซื้อเป็นหลัก

---

## 2. การยกเลิกตามสถานะคำสั่งซื้อ

### 2.1 สถานะ "รอชำระเงิน" (Pending Payment)

**ยกเลิกได้ทันที**

คำสั่งซื้อที่อยู่ในสถานะรอชำระเงินสามารถยกเลิกได้ทันทีโดยไม่มีค่าใช้จ่าย ผ่านแอปพลิ

### 😊1.1.1 Query Rewriter

In [30]:
def rewrite_query(original_query):
    messages = [
        {"role": "system", "content": "You are a helpful assistant specialized in rephrasing user queries to be more effective for information retrieval from a knowledge base. Focus on extracting key entities and concepts. Respond only with the rewritten query, no additional text or explanations."},
        {"role": "user", "content": f"Rewrite the following query for better knowledge base retrieval: '{original_query}'"}
    ]
    rewritten_query = ask_llm(messages)
    return rewritten_query

# Demonstrate the query rewriter
example_original_query = "นาฬิกา S3 Ultra กันน้ำได้แค่ไหน?"
rewritten_q = rewrite_query(example_original_query)

print(f"Original Query: {example_original_query}")
print(f"Rewritten Query: {rewritten_q}")

example_original_query_2 = "อยากรู้ข้อมูลเกี่ยวกับโน้ตบุ๊ก SaiFah"
rewritten_q_2 = rewrite_query(example_original_query_2)

print(f"\nOriginal Query: {example_original_query_2}")
print(f"Rewritten Query: {rewritten_q_2}")

Original Query: นาฬิกา S3 Ultra กันน้ำได้แค่ไหน?
Rewritten Query: <think>
Okay, the user wants me to rephrase their query for better knowledge base retrieval. The original query is "นาฬิกา S3 Ultra กันน้ำได้แค่ไหน?" which translates to "How water-resistant is the S3 Ultra watch?"

First, I need to identify the key entities and concepts here. The main subject is the "นาฬิกา S3 Ultra" (S3 Ultra watch). The key question is about its water resistance. The user is asking about the level of water resistance, so terms like "water resistance level" or "waterproof rating" might be more precise.

I should also consider standard terms used in product specifications. Often, water resistance is measured in meters or atmospheres, so including those terms could help retrieve more accurate information. Maybe "water resistance rating" or "IP rating" would be better.

The original query uses "กันน้ำได้แค่ไหน" which is a bit informal. Replacing it with "water resistance level" or "waterproof rating" would make it more technical and likely to match the knowledge base entries.

Also, specifying the model as "S3 Ultra" is important. Maybe adding "waterproof rating" or "water resistance specifications" could help.

Putting it all together, the rewritten query should focus on the water resistance level of the S3 Ultra watch, using precise terms. So something like "What is the water resistance level of the S3 Ultra watch?" or "What is the waterproof rating of the S3 Ultra watch?"

I should check if there are any other possible terms. Maybe "waterproof specifications" or "water resistance standards". But the most common terms are "water resistance level" and "waterproof rating".

Also, ensuring that the query is concise and includes all necessary entities. The user is asking about the S3 Ultra specifically, so no need to add other models.

Finalizing the rephrased query: "What is the water resistance level of the S3 Ultra watch?" or "What is the waterproof rating of the S3 Ultra watch?" Either should work, but maybe the first one is more direct. Alternatively, "What is the water resistance specification of the S3 Ultra watch?"

Wait, the user might be looking for the exact rating, like IP68 or meters. So including "water resistance rating" or "waterproof rating" would target that.

I think the best approach is to use "water resistance level" as it's a common term in product descriptions. So the final rewritten query would be: "What is the water resistance level of the S3 Ultra watch?"

Alternatively, "What is the waterproof rating of the S3 Ultra watch?" might be better if the knowledge base uses "waterproof rating" as a term. But since the user's original query is in Thai, maybe the knowledge base uses Thai terms. However, the user wants the query to be effective for retrieval, so using English terms might be better if the knowledge base is in English. But the user's query is in Thai, so perhaps the knowledge base is in Thai.

Wait, the user's instruction is to rephrase the query for better knowledge base retrieval. The original query is in Thai, so the knowledge base is likely in Thai. Therefore, using Thai terms would be more effective.

So, translating "water resistance level" into Thai would be "ระดับการกันน้ำ" or "ความสามารถในการกันน้ำ". But the user's original query is "กันน้ำได้แค่ไหน", which is "how water-resistant".

In Thai, "ระดับการกันน้ำ" is a common term. So the rewritten query could be "ระดับการกันน้ำของนาฬิกา S3 Ultra คือเท่าไร?" which translates to "What is the water resistance level of the S3 Ultra watch?"

But the user might prefer a more concise version. Alternatively, "นาฬิกา S3 Ultra มีระดับการกันน้ำเท่าไร?" which is "What is the water resistance level of the S3 Ultra watch?"

Yes, that's better. So the final answer should be "นาฬิกา S3 Ultra มีระดับการกันน้ำเท่าไร?" which directly asks for the water resistance level, using precise Thai terms.
</think>
นาฬิกา S3 Ultra มีระดับการกันน้ำเท่าไร?

Original Query: อยากรู้ข้อมูลเกี่ยวกับโน้ตบุ๊ก SaiFah
Rewritten Query: <think>
Okay, the user wants me to rephrase their query for better knowledge base retrieval. The original query is "อยากรู้ข้อมูลเกี่ยวกับโน้ตบุ๊ก SaiFah". Let me break this down.

First, the main subject is "โน้ตบุ๊ก SaiFah". The user is asking for information about a notebook from the brand SaiFah. The key entities here are "โน้ตบุ๊ก" (notebook) and "SaiFah" (the brand).

I need to make sure that the rewritten query includes these entities clearly. Maybe using "โน้ตบุ๊ก" as "notebook" and "SaiFah" as the brand name. Also, the user might be looking for specific details like specifications, features, or where to buy it. But since the original query is pretty straightforward, the main goal is to extract the key entities.

So, the rewritten query should focus on the brand and the product type. Maybe something like "โน้ตบุ๊ก SaiFah" or "SaiFah notebook". Also, considering that knowledge bases often use specific terminology, using "notebook" instead of "โน้ตบุ๊ก" might help if the system is more familiar with English terms. But the user wrote it in Thai, so maybe keeping it in Thai is better. Wait, the user's query is in Thai, but the knowledge base might be in Thai or English. Hmm, the user's instruction is to rephrase for better retrieval, so perhaps using the exact terms as in the original query is better.

Wait, the user's example response was in Thai. Let me check the example. The user provided an example where the original query was in Thai, and the assistant's response was also in Thai. So, the user probably wants the rewritten query in Thai.

So, the key entities are "โน้ตบุ๊ก" and "SaiFah". The rewritten query should be "โน้ตบุ๊ก SaiFah" or "SaiFah โน้ตบุ๊ก". Maybe "โน้ตบุ๊ก SaiFah" is more natural. Also, adding "ข้อมูล" (information) might not be necessary if the knowledge base already knows the query is about information. But the original query includes "อยากรู้ข้อมูลเกี่ยวกับ", so the user is asking for information. However, the knowledge base might already be designed to handle queries like "โน้ตบุ๊ก SaiFah" and return the relevant info.

So, the best approach is to extract the key entities: "โน้ตบุ๊ก" and "SaiFah", and structure the query around those. The rewritten query could be "โน้ตบุ๊ก SaiFah" or "SaiFah โน้ตบุ๊ก". Maybe "โน้ตบุ๊ก SaiFah" is more direct. Alternatively, "SaiFah โน้ตบุ๊ก" might be better if the brand name comes first.

In Thai, brand names usually come first, so "SaiFah โน้ตบุ๊ก" might be more natural. Let me check. For example, when people search for products, they often put the brand first. So "SaiFah โน้ตบุ๊ก" would be more likely to be found in a knowledge base.

Therefore, the rewritten query should be "SaiFah โน้ตบุ๊ก" to better match how the knowledge base might index the information. That way, the brand name is first, followed by the product type. This should improve retrieval because the knowledge base might have entries structured as "SaiFah โน้ตบุ๊ก" with details about the product.
</think>
SaiFah โน้ตบุ๊ก

### 😊1.2 Chunking

LLMs have limited context windows, and long documents dilute relevance. We split each document into smaller **chunks** using a fixed-size sliding window with overlap.

In [48]:
CHUNK_SIZE = 512
CHUNK_OVERLAP = 128

def make_chunks(text, size, overlap):
    if len(text) <= size: return [text]
    chunks_list = []
    start = 0
    while start < len(text):
        chunks_list.append(text[start : start + size])
        start += size - overlap
    return chunks_list

# ใช้ documents ที่โหลดมาจาก Drive (118 ไฟล์)
chunks = []
for doc in documents:
    for window in make_chunks(doc["text"], CHUNK_SIZE, CHUNK_OVERLAP):
        chunks.append({"text": window, "source": doc["path"]})

print(f"Created {len(chunks)} chunks from {len(documents)} documents")

Created 1055 chunks from 118 documents

###😗 1.3 Embedding

In [24]:
from sentence_transformers import SentenceTransformer

def get_detailed_instruct(task_description: str, query: str) -> str:
    return f'Instruct: {task_description}\nQuery: {query}'

# Each query must come with a one-sentence instruction that describes the task
task = 'Given a web search query, retrieve relevant passages that answer the query'
queries = [
    get_detailed_instruct(task, 'how much protein should a female eat'),
    get_detailed_instruct(task, '南瓜的家常做法')
]
# No need to add instruction for retrieval documents
documents = [
    "As a general guideline, the CDC's average requirement of protein for women ages 19 to 70 is 46 grams per day. But, as you can see from this chart, you'll need to increase that if you're expecting or training for a marathon. Check out the chart below to see how much protein you should be eating each day.",
    "1.清炒南瓜丝 原料:嫩南瓜半个 调料:葱、盐、白糖、鸡精 做法: 1、南瓜用刀薄薄的削去表面一层皮,用勺子刮去瓤 2、擦成细丝(没有擦菜板就用刀慢慢切成细丝) 3、锅烧热放油,入葱花煸出香味 4、入南瓜丝快速翻炒一分钟左右,放盐、一点白糖和鸡精调味出锅 2.香葱炒南瓜 原料:南瓜1只 调料:香葱、蒜末、橄榄油、盐 做法: 1、将南瓜去皮,切成片 2、油锅8成热后,将蒜末放入爆香 3、爆香后,将南瓜片放入,翻炒 4、在翻炒的同时,可以不时地往锅里加水,但不要太多 5、放入盐,炒匀 6、南瓜差不多软和绵了之后,就可以关火 7、撒入香葱,即可出锅"
]
input_texts = queries + documents

model = SentenceTransformer('intfloat/multilingual-e5-large-instruct')

embeddings = model.encode(input_texts, convert_to_tensor=True, normalize_embeddings=True)
scores = (embeddings[:2] @ embeddings[2:].T) * 100
print(scores.tolist())
# [[91.92853546142578, 67.5802993774414], [70.38143157958984, 92.13307189941406]]

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

[[91.9375, 67.625], [70.375, 92.125]]

In [93]:
from sentence_transformers import SentenceTransformer

embed_model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")

# Embed all chunks
chunk_texts = [c["text"] for c in chunks]
chunk_embeddings = embed_model.encode(chunk_texts, batch_size=64, show_progress_bar=True, normalize_embeddings=True)

print(f"Chunk embeddings shape: {chunk_embeddings.shape}")  # (n_chunks, 384)

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/645 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/471M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/526 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/17 [00:00<?, ?it/s]

Chunk embeddings shape: (1055, 384)

### 😎1.4 Retrieve

Embed the question, then find the most similar chunks via dot product (= cosine similarity for normalized vectors).

In [94]:
TOP_K = 5

def dense_retrieve(query, chunk_embs, k=TOP_K):
    """Return indices of top-k most similar chunks to the query."""
    q_emb = embed_model.encode([query], normalize_embeddings=True)
    scores = np.dot(chunk_embs, q_emb.T).flatten()  # cosine similarity (vectors are normalized)
    top_idx = np.argsort(scores)[::-1][:k]
    return top_idx, scores[top_idx]

# Demo: retrieve for Q1
q = questions[0]
idx, scores = dense_retrieve(q["question"], chunk_embeddings)

print(f"Question: {q['question']}\n")
for rank, (i, s) in enumerate(zip(idx, scores), 1):
    print(f"  Rank {rank} (score={s:.3f}) [{chunks[i]['source']}]")
    print(f"  {chunks[i]['text'][:150]}...")
    print()

Question: Watch S3 Ultra กันน้ำได้กี่ ATM ครับ

  Rank 1 (score=0.675) [products/WK-SW-001_wongkhojon_watch_s3_ultra.md]
  ือน** ผ่านบัตรเครดิตที่ร่วมรายการ
(หมดเขต 30 มิถุนายน 2569)

ตัวอย่าง: ฿14,990 ÷ 6 เดือน = เพียง ฿2,498.33/เดือน

---

## คำถามที่พบบ่อยเกี่ยวกับสินค้...

  Rank 2 (score=0.626) [products/WK-SW-003_wongkhojon_watch_s3.md]
  ATM ในราคาที่เข้าถึงได้ง่ายกว่า S3 Pro กว่าครึ่ง

ตัวเรือนอะลูมิเนียมอัลลอยด์เคลือบผิวแบบ anodized ให้ความทนทานและน้ำหนักเบาพร้อมกัน หน้าจอ AMOLED 1.7...

  Rank 3 (score=0.602) [products/WK-SW-002_wongkhojon_watch_s3_pro.md]
  - **NFC Pay:** รองรับการชำระเงินผ่าน FahMai Pay ที่เครื่องรับที่สนับสนุน NFC

---

## โปรโมชันปัจจุบัน

**รับ FahMai Points x2** เมื่อซื้อ Watch S3 Pr...

  Rank 4 (score=0.601) [products/WK-SW-004_wongkhojon_watch_s3_se.md]
  าบสำคัญ:** Watch S3 SE ไม่มี GPS ในตัว (ใช้ GPS จากโทรศัพท์แทน — Connected GPS) ไม่มี ECG และไม่มี NFC Pay มาตรฐานกันน้ำ 3 ATM (30 เมตร) รองรับฝนและกา...

  Rank 5 (score=0.597) [products/WK-SW-003_wongkhojon_watch_s3.md]
   ฿9,990) ความแตกต่างหลักคือ Watch S3 ไม่มี ECG และไม่มี NFC Pay ส่วน S3 Pro มีทั้งสองอย่าง นอกจากนี้ S3 Pro ใช้ตัวเรือนสแตนเลส (หนักกว่าเล็กน้อยแต่ดูพ...

In [36]:
import torch
from sklearn.metrics.pairwise import cosine_similarity

TOP_K = 3 # Define how many top chunks to retrieve

def retrieve_knowledge(query, knowledge_chunks, knowledge_embeddings, top_k=TOP_K):
    # Embed the query
    query_embedding = embedding_model.encode([query], convert_to_tensor=True)

    # Calculate cosine similarity
    similarities = cosine_similarity(query_embedding.cpu().numpy(), knowledge_embeddings.cpu().numpy())[0]

    # Get the indices of the top-k most similar chunks
    top_indices = similarities.argsort()[-top_k:][::-1]

    # Retrieve the actual chunks
    retrieved_chunks = [knowledge_chunks[i] for i in top_indices]
    return retrieved_chunks, similarities[top_indices]

# Demo retrieval
example_query = "มีแบรนด์อะไรบ้างในร้าน?"
retrieved_info, scores = retrieve_knowledge(example_query, knowledge_chunks_raw, knowledge_embeddings)

print(f"Query: '{example_query}'")
print("Top retrieved information:")
for i, (chunk, score) in enumerate(zip(retrieved_info, scores)):
    print(f"  {i+1}. Score: {score:.4f} - {chunk}")

Query: 'มีแบรนด์อะไรบ้างในร้าน?'
Top retrieved information:
  1. Score: 0.7661 - The store is called Thailand's electronics store.
  2. Score: 0.7543 - In the Audio category, we have Headphones, speakers, and soundbars from KluenSiang and other brands.
  3. Score: 0.7516 - In the Phones category, we have Smartphones from various brands, including SaiFah and DaoNuea.

### 🔑1.5 Generate Answer

Now, let's combine the retrieved context with the user's question and send it to the LLM to generate a coherent answer.

In [98]:
# A very basic system prompt — you should improve this!
SYSTEM_PROMPT = "ตอบคำถามจากข้อมูลที่ให้มา เลือกตัวเลือกที่ถูกต้องที่สุด ตอบเป็น ANSWER: X เท่านั้น ห้ามแสดงความคิดเห็นหรือขั้นตอนการวิเคราะห์ใดๆ"

def build_rag_prompt(question, choices, retrieved_chunks):
    context = "\n\n".join(
        f"--- Chunk {i+1} ---\n{c['text']}"
        for i, c in enumerate(retrieved_chunks)
    )
    choices_text = "\n".join(f"{k}. {v}" for k, v in choices.items())
    return (
        f"{context}\n\n"
        f"คำถาม: {question}\n\n"
        f"ตัวเลือก:\n{choices_text}\n\n"
        f"ตอบ ANSWER: X (X คือหมายเลขตัวเลือก 1-10)"
    )

# Demo: answer Q1
q = questions[0]
idx, _ = dense_retrieve(q["question"], chunk_embeddings)
retrieved = [chunks[i] for i in idx]

prompt = build_rag_prompt(q["question"], q["choices"], retrieved)
raw = ask_llm([
    {"role": "system", "content": SYSTEM_PROMPT},
    {"role": "user", "content": prompt},
])

# Clean up the output by removing the <think> blocks before printing
clean_raw = re.sub(r"<think>.*?</think>", "", raw, flags=re.DOTALL).strip()
answer = parse_answer(raw)

print(f"คำถามคืออะไร: {q['question']}")
print(f"LLM ตอบว่าอย่างไร: {clean_raw}")
print(f"parsed answer คืออะไร: {answer}")

คำถามคืออะไร: Watch S3 Ultra กันน้ำได้กี่ ATM ครับ
LLM ตอบว่าอย่างไร: ANSWER: 5
parsed answer คืออะไร: 5

In [99]:
retrieved

[{'text': 'ือน** ผ่านบัตรเครดิตที่ร่วมรายการ\n(หมดเขต 30 มิถุนายน 2569)\n\nตัวอย่าง: ฿14,990 ÷ 6 เดือน = เพียง ฿2,498.33/เดือน\n\n---\n\n## คำถามที่พบบ่อยเกี่ยวกับสินค้านี้\n\n**Q: Watch S3 Ultra ต่างจาก Watch S3 Pro ยังไงบ้างครับ?**\nA: S3 Ultra แตกต่างจาก S3 Pro ในหลายด้านครับ ได้แก่ (1) ตัวเรือนไทเทเนียม เบากว่าสแตนเลสของ S3 Pro, (2) กันน้ำ 100 เมตร พร้อม Dive Mode — S3 Pro กันน้ำ 50 เมตรแต่ไม่มี Dive Mode, (3) GPS แบบ Dual-Band แม่นยำกว่า S3 Pro ที่เป็น Single-Band, (4) หน้าจอใหญ่กว่า 1.9 นิ้ว vs 1.7 นิ้ว, (5) แบตเตอรี่อึดก',
  'source': 'products/WK-SW-001_wongkhojon_watch_s3_ultra.md'},
 {'text': 'ATM ในราคาที่เข้าถึงได้ง่ายกว่า S3 Pro กว่าครึ่ง\n\nตัวเรือนอะลูมิเนียมอัลลอยด์เคลือบผิวแบบ anodized ให้ความทนทานและน้ำหนักเบาพร้อมกัน หน้าจอ AMOLED 1.7 นิ้วที่มีความสว่าง 1,000 nits ใช้งานได้แม้กลางแดด สีสันสดใส ประหยัดพลังงาน ทำให้แบตเตอรี่อยู่ได้นานถึง 18 ชั่วโมงในโหมดใช้งานเต็มรูปแบบ หรือสูงสุด 10 วันในโหมดประหยัด\n\nGPS single-band รองรับดาวเทียม GPS และ GLONASS ติดตามเส้นทางการออกกำลังกายได้แม่นยำในพื้นที่กลางแจ้ง รองรับโหมดกีฬา 100+ ประเภท ตั้งแต่วิ่ง ปั่น ว่ายน้ำ ไปจนถึงโยคะและพิลาทีส เซ็นเซอร์ SpO2 วัด',
  'source': 'products/WK-SW-003_wongkhojon_watch_s3.md'},
 {'text': '- **NFC Pay:** รองรับการชำระเงินผ่าน FahMai Pay ที่เครื่องรับที่สนับสนุน NFC\n\n---\n\n## โปรโมชันปัจจุบัน\n\n**รับ FahMai Points x2** เมื่อซื้อ Watch S3 Pro ในช่วงโปรโมชัน\n(หมดเขต 31 มีนาคม 2569)\n\nPoints ที่ได้รับจะถูกเครดิตเข้าบัญชีภายใน 7 วันทำการหลังจากได้รับสินค้า\n\n---\n\n## คำถามที่พบบ่อยเกี่ยวกับสินค้านี้\n\n**Q: Watch S3 Pro มี ECG ไหมครับ? ต่างจาก Watch S3 ยังไง?**\nA: มีครับ Watch S3 Pro มีฟังก์ชัน ECG (คลื่นไฟฟ้าหัวใจ) ครบ นี่คือความแตกต่างหลักจาก Watch S3 (WK-SW-003) ที่ไม่มี ECG ส่วนฟีเจอร์อื่นอย่าง SpO2,',
  'source': 'products/WK-SW-002_wongkhojon_watch_s3_pro.md'},
 {'text': 'าบสำคัญ:** Watch S3 SE ไม่มี GPS ในตัว (ใช้ GPS จากโทรศัพท์แทน — Connected GPS) ไม่มี ECG และไม่มี NFC Pay มาตรฐานกันน้ำ 3 ATM (30 เมตร) รองรับฝนและการล้างมือ แต่ไม่เหมาะสำหรับว่ายน้ำเป็นเวลานาน หากต้องการ GPS ในตัวหรือกันน้ำสำหรับว่ายน้ำ แนะนำ Watch S3 (WK-SW-003)\n\n---\n\n## สเปคสินค้า\n\n| รายการ | รายละเอียด |\n|--------|-----------|\n| หน้าจอ | 1.7 นิ้ว LCD TFT |\n| ความละเอียดหน้าจอ | 360 × 360 พิกเซล |\n| ความสว่าง | สูงสุด 450 nits |\n| วัสดุตัวเรือน | Polymer (PC+ABS) |\n| กระจกหน้าจอ | Tempered Glass |\n| GPS',
  'source': 'products/WK-SW-004_wongkhojon_watch_s3_se.md'},
 {'text': ' ฿9,990) ความแตกต่างหลักคือ Watch S3 ไม่มี ECG และไม่มี NFC Pay ส่วน S3 Pro มีทั้งสองอย่าง นอกจากนี้ S3 Pro ใช้ตัวเรือนสแตนเลส (หนักกว่าเล็กน้อยแต่ดูพรีเมียมกว่า) ถ้าไม่ได้ต้องการ ECG หรือจ่ายเงินผ่านนาฬิกา Watch S3 คุ้มค่ามากครับ\n\n**Q: Watch S3 มี ECG ไหมคะ?**\nA: ไม่มีค่ะ Watch S3 ไม่มีฟีเจอร์ ECG ถ้าต้องการ ECG ต้องเลือก Watch S3 Pro (WK-SW-002) ขึ้นไป S3 มีแค่ HR และ SpO2 เท่านั้น\n\n**Q: โหมดกีฬามีกี่ประเภทครับ?**\nA: รองรับกีฬามากกว่า 100 ประเภทครับ ครอบคลุมกีฬาหลัก เช่น วิ่ง เดิน ปั่นจักรยาน ว่ายน้ำ ไปจน',
  'source': 'products/WK-SW-003_wongkhojon_watch_s3.md'}]

In [37]:
import os
import csv
import pandas as pd

# Define the directory where data is expected
# Adjust this path if your data is located elsewhere
DATA_DIR = "/content/drive/MyDrive/H3_datanaja/data"

print(f"--- Listing files in {DATA_DIR} ---")

questions = [] # Initialize questions as an empty list

if os.path.exists(DATA_DIR):
    all_files = os.listdir(DATA_DIR)
    found_question_csv = False
    for f in all_files:
        # Look for a CSV file that contains 'question' in its name (case-insensitive)
        if "question" in f.lower() and f.endswith(".csv"):
            file_path = os.path.join(DATA_DIR, f)
            print(f"✅ Found questions CSV: {f}")

            try:
                df_questions = pd.read_csv(file_path)
                print(f"✅ Successfully loaded {len(df_questions)} questions.")
                # Convert DataFrame to the required 'questions' list format
                for _, row in df_questions.iterrows():
                    choices = {str(i): row[f'choice_{i}'] for i in range(1, 11) if f'choice_{i}' in row}
                    questions.append({"id": int(row['id']), "question": row['question'], "choices": choices})
                found_question_csv = True
                display(df_questions.head(3))
            except Exception as e:
                print(f"❌ Error reading CSV file: {e}")
            break # Stop after finding and processing the first matching CSV

    if not found_question_csv:
        print("❌ No 'question' CSV file found in the specified directory.")
        print("Please ensure your questions CSV (e.g., 'questions.csv') is uploaded to:")
        print(f"  {DATA_DIR}")
        print("If it's a Google Sheet, you may need to download it as a .csv file and upload it to your Drive.")
else:
    print(f"❌ Data directory not found: {DATA_DIR}")
    print("Please ensure your Google Drive is mounted correctly and the path is accurate.")

# Placeholder for chunks, assuming it's needed for run_pipeline or BM25
# For now, we'll make a simple list of dicts from knowledge_chunks_raw
chunks = [{'text': chunk, 'source': f'knowledge_base_chunk_{i}'} for i, chunk in enumerate(knowledge_chunks_raw)]

def run_pipeline(questions_list, retrieve_func, label="dense", n=None):
    """Placeholder function to simulate running the RAG pipeline over questions."""
    print(f"Running pipeline with {label} retrieval...")
    preds = {}
    questions_to_process = questions_list[:n] if n else questions_list

    for i, q in enumerate(questions_to_process):
        print(f"  Processing question {i+1}/{len(questions_to_process)} (ID: {q['id']})...")
        # In a real scenario, this would call retrieve_func and generate an answer
        # For now, we'll just store a dummy prediction
        preds[q['id']] = 1 # Dummy answer for now

    print(f"Pipeline {label} finished. Processed {len(preds)} questions.")
    return preds

print("\n'questions' variable and 'run_pipeline' function prepared.")

--- Listing files in /content/drive/MyDrive/H3_datanaja/data ---
✅ Found questions CSV: questions.csv
✅ Successfully loaded 100 questions.

,id,question,choice_1,choice_2,choice_3,choice_4,choice_5,choice_6,choice_7,choice_8,choice_9,choice_10
0,1,Watch S3 Ultra กันน้ำได้กี่ ATM ครับ,3 ATM,IP68,5 ATM,IP67,10 ATM,20 ATM,IPX8,1 ATM,ไม่มีข้อมูลนี้ในฐานข้อมูล,คำถามนี้ไม่เกี่ยวข้องกับฐานข้อมูลสินค้า
1,2,ปากกา SaiFah Pen Gen 2 ราคาเท่าไหร่คะ,"2,990 บาท","4,490 บาท","1,990 บาท","4,990 บาท","3,490 บาท","2,490 บาท","3,990 บาท","5,490 บาท",ไม่มีข้อมูลนี้ในฐานข้อมูล,คำถามนี้ไม่เกี่ยวข้องกับฐานข้อมูลสินค้า
2,3,หูฟัง HeadPro X1 ใช้ Bluetooth เวอร์ชันอะไรคะ,Bluetooth 5.0,Bluetooth 5.3,Bluetooth 5.4,Bluetooth 4.2,Bluetooth 5.2,Bluetooth 5.1,Bluetooth 4.0,Bluetooth 5.5,ไม่มีข้อมูลนี้ในฐานข้อมูล,คำถามนี้ไม่เกี่ยวข้องกับฐานข้อมูลสินค้า

'questions' variable and 'run_pipeline' function prepared.

In [38]:
def generate_answer_with_context(query, retrieved_chunks):
    context = "\n".join(retrieved_chunks)
    messages = [
        {"role": "system", "content": "You are a helpful assistant for Thailand's electronics store. Answer the user's question concisely based *only* on the provided context. If the answer is not in the context, state that you don't have enough information.\nContext:" + context},
        {"role": "user", "content": query}
    ]
    return ask_llm(messages)

# Demo answer generation
example_query_2 = "มีแบรนด์โทรศัพท์อะไรบ้าง?"
retrieved_info_2, _ = retrieve_knowledge(example_query_2, knowledge_chunks_raw, knowledge_embeddings)

print(f"Query: '{example_query_2}'")
print("Retrieved context:")
for i, chunk in enumerate(retrieved_info_2):
    print(f"  {i+1}. {chunk}")

llm_answer = generate_answer_with_context(example_query_2, retrieved_info_2)
print("\nLLM Answer (with RAG context):")
print(llm_answer)

Query: 'มีแบรนด์โทรศัพท์อะไรบ้าง?'
Retrieved context:
  1. In the Phones category, we have Smartphones from various brands, including SaiFah and DaoNuea.
  2. In the Audio category, we have Headphones, speakers, and soundbars from KluenSiang and other brands.
  3. The store is called Thailand's electronics store.

LLM Answer (with RAG context):
<think>
Okay, the user is asking about the brands of phones available in the store. Let me check the context provided.

In the Phones category, the context mentions that there are Smartphones from various brands, including SaiFah and DaoNuea. So those two brands are listed. The other brands aren't specified, but the user is asking specifically for the brands mentioned. Since the context only names SaiFah and DaoNuea, I should list those. I need to make sure not to include any other brands that aren't mentioned. The answer should be concise and only include the information from the context. If there were more brands, they would have been listed, but since they aren't, I'll stick to the two provided.
</think>
ในหมวดหมู่โทรศัพท์ ทางร้านมีสมาร์ทโฟนจากแบรนด์ต่างๆ รวมถึง **SaiFah** และ **DaoNuea**

In [64]:
# Re-calculate Embeddings with Batch processing to avoid Interrupt
import torch
print("Generating embeddings for all chunks in batches...")

# Encode in batches to be safer
chunk_list = [c['text'] for c in chunks]
chunk_embeddings = embedding_model.encode(chunk_list,
                                          batch_size=32,
                                          show_progress_bar=True,
                                          convert_to_tensor=True,
                                          normalize_embeddings=True)

SYSTEM_PROMPT = """คุณคือผู้ช่วยตอบคำถามของร้าน 'ฟ้าใหม่' (FahMai)
ใช้ข้อมูลจาก Context ที่ให้มาเพื่อเลือกคำตอบที่ถูกต้องที่สุดจากตัวเลือกที่กำหนด
- ตอบเป็นหมายเลขข้อเท่านั้น เช่น ANSWER: 1
- หากไม่พบข้อมูลใน Context ให้ตอบข้อ 'ไม่มีข้อมูลนี้ในฐานข้อมูล'
- หากไม่เกี่ยวกับร้าน ให้ตอบข้อ 'คำถามนี้ไม่เกี่ยวข้องกับฐานข้อมูลสินค้า'"""

def dense_retrieve(query, k=3):
    from sklearn.metrics.pairwise import cosine_similarity
    task = 'Given a web search query, retrieve relevant passages that answer the query'
    formatted_query = f'Instruct: {task}\nQuery: {query}'
    query_emb = embedding_model.encode([formatted_query], convert_to_tensor=True, normalize_embeddings=True)
    sims = cosine_similarity(query_emb.cpu().numpy(), chunk_embeddings.cpu().numpy())[0]
    top_indices = sims.argsort()[-k:][::-1]
    return top_indices, sims[top_indices]

print(f"✓ Processed {len(chunk_embeddings)} embeddings.")

Generating embeddings for all chunks in batches...

Batches:   0%|          | 0/33 [00:00<?, ?it/s]

✓ Processed 1055 embeddings.

In [89]:
def generate_answer_llm(query, retrieved_chunks):
    """Answer the question using Typhoon (ThaiLLM) only."""
    context = "\n\n".join([f"Context {i+1}: {c['text']}" for i, c in enumerate(retrieved_chunks)])
    instruction = f"Answer the question strictly using the provided context.\nContext:\n{context}"

    messages = [
        {"role": "system", "content": instruction},
        {"role": "user", "content": query}
    ]
    return ask_llm(messages, model="typhoon")

print("Pipeline set to use Typhoon exclusively.")

Pipeline set to use Typhoon exclusively.

### 1.6 Run All Questions (Dense)

Loop through questions, retrieve, generate, and collect predictions.

In [102]:
def run_pipeline(questions, retrieve_fn, label="dense", n=10):
    """Run retrieval + LLM on first n questions. Returns predictions dict."""
    predictions = {}
    for i, q in enumerate(questions[:n]):
        retrieved_chunks = retrieve_fn(q["question"])
        prompt = build_rag_prompt(q["question"], q["choices"], retrieved_chunks)
        raw = ask_llm([
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt},
        ])

        # Use the same cleanup logic as the demo
        clean_raw = re.sub(r"<think>.*?</think>", "", raw, flags=re.DOTALL).strip()
        pred = parse_answer(raw)

        predictions[q["id"]] = pred if pred else 9
        print(f"  Q{q['id']:>3}: pred={predictions[q['id']]} | raw={clean_raw}")

        # Increase sleep time to be safer against rate limits
        time.sleep(1.0)

    print(f"\n{label}: answered {len(predictions)} questions")
    return predictions

# Dense retrieval function
def dense_retrieve_chunks(query):
    idx, _ = dense_retrieve(query, chunk_embeddings)
    return [chunks[i] for i in idx]

# Run for 10 questions
dense_preds = run_pipeline(questions, dense_retrieve_chunks, label="dense", n=10)

  Q  1: pred=5 | raw=ANSWER: 5
  Q  2: pred=7 | raw=ANSWER: 7
  Q  3: pred=2 | raw=ANSWER: 2
  Q  4: pred=6 | raw=ANSWER: 6
  Q  5: pred=6 | raw=ANSWER: 6
  Q  6: pred=8 | raw=ANSWER: 8
  Q  7: pred=1 | raw=ANSWER: 1
  Q  8: pred=4 | raw=ANSWER: 4
  Error: 502 Server Error: Bad Gateway for url: http://thaillm.or.th/api/pathumma/v1/chat/completions, retrying in 1s...
  Error: 504 Server Error: Gateway Timeout for url: http://thaillm.or.th/api/pathumma/v1/chat/completions, retrying in 2s...
  Error: 502 Server Error: Bad Gateway for url: http://thaillm.or.th/api/pathumma/v1/chat/completions, retrying in 4s...
  Q  9: pred=7 | raw=ANSWER: 7
  Q 10: pred=2 | raw=ANSWER: 2

dense: answered 10 questions

In [90]:
def run_pipeline(questions_list, n=5):
    results = {}
    for q in questions_list[:n]:
        # 1. Retrieve relevant chunks
        idx, _ = dense_retrieve(q['question'], k=3)
        retrieved_chunks = [chunks[i] for i in idx]

        # 2. Format Choices for LLM
        choices_text = "\n".join([f"{k}. {v}" for k, v in q['choices'].items()])
        user_input = f"Question: {q['question']}\nChoices:\n{choices_text}"

        # 3. Ask Typhoon
        raw_response = generate_answer_llm(user_input, retrieved_chunks)

        # 4. Parse the Answer (extracting the choice number)
        ans = parse_answer(raw_response)
        results[q['id']] = ans if ans else 9
        print(f"ID: {q['id']} | Pred: {results[q['id']]} | Query: {q['question'][:30]}...")
    return results

# Run sample to verify Typhoon-only operation
final_preds = run_pipeline(questions, n=5)

ID: 1 | Pred: 2 | Query: Watch S3 Ultra กันน้ำได้กี่ AT...
ID: 2 | Pred: 3 | Query: ปากกา SaiFah Pen Gen 2 ราคาเท่...
ID: 3 | Pred: 2 | Query: หูฟัง HeadPro X1 ใช้ Bluetooth...
ID: 4 | Pred: 6 | Query: อยากเอามือถือเครื่องเก่ามาเทิร...
ID: 5 | Pred: 1 | Query: สั่งของจากฟ้าใหม่ สั่งได้ครั้ง...

- เเก้ บัคไม่อยู่ในฐานข้อมูล

In [87]:
# สร้าง Ground Truth Mapping เพื่อตรวจสอบความแม่นยำของการดึงข้อมูล
ground_truth_mapping = {}
for q in questions[:10]:
    idx, scores = dense_retrieve(q['question'], k=1)
    ground_truth_mapping[q['id']] = {
        "question": q['question'],
        "source_file": chunks[idx[0]]['source'],
        "score": float(scores[0])
    }

print("--- Ground Truth Verification (Top-1 Retrieval) ---")
for qid, info in ground_truth_mapping.items():
    print(f"ID {qid}: {info['source_file']} (Score: {info['score']:.4f})")
    print(f"   Q: {info['question'][:60]}...")

--- Ground Truth Verification (Top-1 Retrieval) ---
ID 1: products/WK-SW-002_wongkhojon_watch_s3_pro.md (Score: 0.8643)
   Q: Watch S3 Ultra กันน้ำได้กี่ ATM ครับ...
ID 2: products/JC-CS-006_judchuam_saifah_pen_gen2.md (Score: 0.9143)
   Q: ปากกา SaiFah Pen Gen 2 ราคาเท่าไหร่คะ...
ID 3: products/KS-HP-001_kluensiang_headpro_x1.md (Score: 0.8652)
   Q: หูฟัง HeadPro X1 ใช้ Bluetooth เวอร์ชันอะไรคะ...
ID 4: store_info/general_faq.md (Score: 0.8728)
   Q: อยากเอามือถือเครื่องเก่ามาเทิร์น เปลี่ยนเป็นเครื่องใหม่ที่ฟ้...
ID 5: store_info/general_faq.md (Score: 0.8922)
   Q: สั่งของจากฟ้าใหม่ สั่งได้ครั้งละกี่ชิ้นครับ...
ID 6: store_info/general_faq.md (Score: 0.9008)
   Q: ฟ้าใหม่จ่ายด้วย crypto ได้มั้ยคะ เช่น Bitcoin...
ID 7: products/DN-LT-003_daonuea_airbook_14_8gb.md (Score: 0.8815)
   Q: ซื้อ AirBook 14 มาแล้ว อยากรู้ว่าในกล่องมีอะไรมาบ้าง...
ID 8: products/SF-SP-012_saifah_phone_pocketmini.md (Score: 0.8674)
   Q: DuoPad สั่งซื้อได้เลยไหมครับ หรือต้องพรีออเดอร์...
ID 9: products/SF-SP-015_saifah_phone_rugged_r1.md (Score: 0.8748)
   Q: เฮ้ยย อ่านเยอะมากเลย ขอถามนิดนึงนะคะ คือพอดีว่าจะไปเที่ยวภูเ...
ID 10: products/SF-SP-003_saifah_phone_x9.md (Score: 0.8846)
   Q: อยากใช้ซิม 2 ค่ายพร้อมกันครับ ใส่ซิมได้ 2 ใบมั้ย ไม่อยากพกมื...

---
## Section 2: Sparse Retrieval (BM25)

**BM25** is a keyword-matching algorithm. It scores documents by how many query terms they contain, weighted by term rarity (IDF). No neural network needed.

### 2.1 Thai Tokenization

BM25 needs tokenized text. Thai has no spaces between words, so we use `pythainlp` to segment.

In [103]:
from pythainlp.tokenize import word_tokenize

# Demo: tokenize a Thai sentence
sample = "Watch S3 Ultra กันน้ำได้กี่ ATM ครับ?"
tokens = word_tokenize(sample, engine="newmm")
print(f"Input:  {sample}")
print(f"Tokens: {tokens}")

Input:  Watch S3 Ultra กันน้ำได้กี่ ATM ครับ?
Tokens: ['Watch', ' ', 'S', '3', ' ', 'Ultra', ' ', 'กันน้ำ', 'ได้', 'กี่', ' ', 'ATM', ' ', 'ครับ', '?']

### 2.2 Build BM25 Index

In [104]:
# Re-build BM25 for the REAL documents
from rank_bm25 import BM25Okapi
from pythainlp.tokenize import word_tokenize

tokenized_chunks = [word_tokenize(c["text"], engine="newmm") for c in chunks]
bm25 = BM25Okapi(tokenized_chunks)
print(f"BM25 index re-built over {len(tokenized_chunks)} REAL chunks")

BM25 index re-built over 1055 REAL chunks

### 2.3 Retrieve with BM25

Compare BM25 results with dense results for the same question.

In [105]:
def bm25_retrieve(query, k=TOP_K):
    """Return top-k chunk indices using BM25."""
    tokens = word_tokenize(query, engine="newmm")
    scores = bm25.get_scores(tokens)
    top_idx = np.argsort(scores)[::-1][:k]
    return top_idx, scores[top_idx]

# Compare: same question, two retrieval methods
q = questions[0]
print(f"Question: {q['question']}\n")

d_idx, _ = dense_retrieve(q["question"], chunk_embeddings)
b_idx, _ = bm25_retrieve(q["question"])

print("Dense top-5 sources:")
for i in d_idx:
    print(f"  {chunks[i]['source']}")

print("\nBM25 top-5 sources:")
for i in b_idx:
    print(f"  {chunks[i]['source']}")

Question: Watch S3 Ultra กันน้ำได้กี่ ATM ครับ

Dense top-5 sources:
  products/WK-SW-001_wongkhojon_watch_s3_ultra.md
  products/WK-SW-003_wongkhojon_watch_s3.md
  products/WK-SW-002_wongkhojon_watch_s3_pro.md
  products/WK-SW-004_wongkhojon_watch_s3_se.md
  products/WK-SW-003_wongkhojon_watch_s3.md

BM25 top-5 sources:
  products/WK-SW-002_wongkhojon_watch_s3_pro.md
  products/WK-SW-002_wongkhojon_watch_s3_pro.md
  products/WK-SW-001_wongkhojon_watch_s3_ultra.md
  products/WK-SW-003_wongkhojon_watch_s3.md
  products/WK-SW-001_wongkhojon_watch_s3_ultra.md

### 2.4 Run All Questions (BM25) ❌

In [113]:
def bm25_retrieve_chunks(query):
    idx, _ = bm25_retrieve(query)
    return [chunks[i] for i in idx]

# Run BM25 pipeline for 10 questions with safer timing
bm25_preds = run_pipeline(questions, bm25_retrieve_chunks, label="bm25", n=10)

  Q  1: pred=5 | raw=ANSWER: 5
  Q  2: pred=7 | raw=ANSWER: 7
  Q  3: pred=9 | raw=ANSWER: 9
  Q  4: pred=6 | raw=ANSWER: 6
  Q  5: pred=6 | raw=ANSWER: 6
  Q  6: pred=9 | raw=ANSWER: 9
  Q  7: pred=9 | raw=ANSWER: 9
  Q  8: pred=9 | raw=ANSWER: 9
  Q  9: pred=9 | raw=ANSWER: 9
  Q 10: pred=2 | raw=ANSWER: 2

bm25: answered 10 questions

---
## Section 3: Hybrid Retrieval (RRF)

**Hybrid** combines dense and sparse results. The idea: dense is good at semantic matching, BM25 is good at exact keyword matching. Together they cover more cases.

We use **Reciprocal Rank Fusion (RRF)** to merge the two ranked lists:

$$\text{score}(d) = \sum_{r \in \text{rankers}} \frac{1}{k + \text{rank}_r(d)}$$

where $k$ is a constant (typically 60). Documents ranked highly by *either* method get a high combined score.

In [114]:
def hybrid_retrieve(query, chunk_embs, k=TOP_K, rrf_k=60):
    """Combine dense + BM25 results using Reciprocal Rank Fusion."""
    # Get top candidates from each method (fetch more than k to improve fusion)
    fetch_k = k * 2
    d_idx, _ = dense_retrieve(query, chunk_embs, k=fetch_k)
    b_idx, _ = bm25_retrieve(query, k=fetch_k)

    # Compute RRF scores
    rrf_scores = {}
    for rank, idx in enumerate(d_idx, 1):
        rrf_scores[idx] = rrf_scores.get(idx, 0) + 1.0 / (rrf_k + rank)
    for rank, idx in enumerate(b_idx, 1):
        rrf_scores[idx] = rrf_scores.get(idx, 0) + 1.0 / (rrf_k + rank)

    # Sort by combined score, return top-k
    sorted_idx = sorted(rrf_scores.keys(), key=lambda x: rrf_scores[x], reverse=True)[:k]
    return sorted_idx

# Demo
q = questions[0]
h_idx = hybrid_retrieve(q["question"], chunk_embeddings)
print(f"Question: {q['question']}\n")
print("Hybrid top-5 sources:")
for i in h_idx:
    print(f"  {chunks[i]['source']}")

Question: Watch S3 Ultra กันน้ำได้กี่ ATM ครับ

Hybrid top-5 sources:
  products/WK-SW-001_wongkhojon_watch_s3_ultra.md
  products/WK-SW-003_wongkhojon_watch_s3.md
  products/WK-SW-001_wongkhojon_watch_s3_ultra.md
  products/WK-SW-002_wongkhojon_watch_s3_pro.md
  products/WK-SW-003_wongkhojon_watch_s3.md

### 3.2 Run All Questions (Hybrid)❌

In [115]:
def hybrid_retrieve_chunks(query):
    idx = hybrid_retrieve(query, chunk_embeddings)
    return [chunks[i] for i in idx]

hybrid_preds = run_pipeline(questions, hybrid_retrieve_chunks, label="hybrid")

  Q  1: pred=5 | raw=ANSWER: 5
  Q  2: pred=7 | raw=ANSWER: 7
  Q  3: pred=9 | raw=ANSWER: 9
  Q  4: pred=6 | raw=ANSWER: 6
  Q  5: pred=6 | raw=ANSWER: 6
  Q  6: pred=8 | raw=ANSWER: 8
  Error: 502 Server Error: Bad Gateway for url: http://thaillm.or.th/api/pathumma/v1/chat/completions, retrying in 1s...
  Q  7: pred=9 | raw=ANSWER: 9
  Q  8: pred=4 | raw=ANSWER: 4
  Q  9: pred=9 | raw=ANSWER: 9
  Error: 504 Server Error: Gateway Timeout for url: http://thaillm.or.th/api/pathumma/v1/chat/completions, retrying in 1s...
  Q 10: pred=2 | raw=ANSWER: 2

hybrid: answered 10 questions

### 3.3 Compare All Three Methods

In [110]:
print(f"{'QID':>4}  {'Dense':>6} {'BM25':>6} {'Hybrid':>7}")
print("-" * 30)
for q in questions[:N_QUESTIONS]:
    qid = q["id"]
    d = dense_preds.get(qid, "-")
    b = bm25_preds.get(qid, "-")
    h = hybrid_preds.get(qid, "-")
    match = "" if d == b == h else "  ← differ"
    print(f"Q{qid:>3}  {d:>6} {b:>6} {h:>7}{match}")

 QID   Dense   BM25  Hybrid
------------------------------
Q  1       5      5       5
Q  2       7      7       7
Q  3       2      9       9  ← differ
Q  4       6      6       6
Q  5       6      6       6

In [112]:
# Use dense predictions as the submission (change to hybrid_preds or bm25_preds to try others)
best_preds = dense_preds

with open("submission.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(["id", "answer"])
    for q in questions:
        qid = q["id"]
        writer.writerow([qid, best_preds.get(qid, 1)])  # default=1 for unanswered

print(f"submission.csv written ({len(questions)} rows)")

submission.csv written (100 rows)

In [116]:
# Use dense predictions as the submission (change to hybrid_preds or bm25_preds to try others)
best_preds = dense_preds

with open("submission.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(["id", "answer"])
    for q in questions:
        qid = q["id"]
        # Get the predicted answer from our LLM run, default to 1 if not processed
        final_answer = best_preds.get(qid, 1)
        writer.writerow([qid, final_answer])

print(f"submission.csv written successfully with {len(questions)} rows.")
# Display the first few rows to verify
import pandas as pd
display(pd.read_csv("submission.csv").head(15))

submission.csv written successfully with 100 rows.

    id  answer
0    1       5
1    2       7
2    3       2
3    4       6
4    5       6
5    6       8
6    7       1
7    8       4
8    9       7
9   10       2
10  11       1
11  12       1
12  13       1
13  14       1
14  15       1

In [118]:
import pandas as pd

# Load and display the full submission file
submission_df = pd.read_csv('submission.csv')
pd.set_option('display.max_rows', 100)
display(submission_df)

     id  answer
0     1       5
1     2       7
2     3       2
3     4       6
4     5       6
5     6       8
6     7       1
7     8       4
8     9       7
9    10       2
10   11       1
11   12       1
12   13       1
13   14       1
14   15       1
15   16       1
16   17       1
17   18       1
18   19       1
19   20       1
20   21       1
21   22       1
22   23       1
23   24       1
24   25       1
25   26       1
26   27       1
27   28       1
28   29       1
29   30       1
30   31       1
31   32       1
32   33       1
33   34       1
34   35       1
35   36       1
36   37       1
37   38       1
38   39       1
39   40       1
40   41       1
41   42       1
42   43       1
43   44       1
44   45       1
45   46       1
46   47       1
47   48       1
48   49       1
49   50       1
50   51       1
51   52       1
52   53       1
53   54       1
54   55       1
55   56       1
56   57       1
57   58       1
58   59       1
59   60       1
60   61       1
61   62       1
62   63       1
63   64       1
64   65       1
65   66       1
66   67       1
67   68       1
68   69       1
69   70       1
70   71       1
71   72       1
72   73       1
73   74       1
74   75       1
75   76       1
76   77       1
77   78       1
78   79       1
79   80       1
80   81       1
81   82       1
82   83       1
83   84       1
84   85       1
85   86       1
86   87       1
87   88       1
88   89       1
89   90       1
90   91       1
91   92       1
92   93       1
93   94       1
94   95       1
95   96       1
96   97       1
97   98       1
98   99       1
99  100       1

In [119]:
from google.colab import files
try:
    files.download('submission.csv')
    print('กำลังส่งไฟล์ submission.csv ให้ดาวน์โหลดครับ...')
except Exception as e:
    print(f'ไม่พบไฟล์: {e}')

กำลังส่งไฟล์ submission.csv ให้ดาวน์โหลดครับ...